TRUNCATE TABLE prenotazione_classe RESTART IDENTITY CASCADE;
TRUNCATE TABLE prenotazione        RESTART IDENTITY CASCADE;
TRUNCATE TABLE classe              RESTART IDENTITY CASCADE;
TRUNCATE TABLE aula                RESTART IDENTITY CASCADE;
TRUNCATE TABLE utente              RESTART IDENTITY CASCADE;
